### PR TITLE
Refactor create dates

### PR DESCRIPTION
**Pull request by ZooeyMiller**
I've worked a little on refactoring the createDates function, it's now a little more granular and is exported as an object with two methods and a property, the property is a new Date() instance, the first method takes a date object and converts it to the format we need, and the second takes that formatted date and returns an array of dates going back 10 years. 

I've also written tests for both of these methods, not exhaustive ones, but they test that when given a valid input they will give back what we hope for, they should probably be refactored to put in some error handling, though as far as I can see there are minimal errors possible since we will probably be calling these functions in some kind of compilation function and thus dictationg ho they are called an what they are called with. 

relates to #3

### CODE REVIEW

**Comment by ZooeyMiller** [comment]
Not really sure why the codecov in the checks are showing as unsuccessful when the comment from codecov clearly shows 100% coverage. Hmmm. :thinking:

**Comment by ZooeyMiller** [comment]
Oh I forgot to mention in the body of the PR, I also installed faucet as a dev dependacy as it wasn't one already (was giving me some odd errors).

**Comment by oliverjam** [comment]
That looks cool. Any reason you changed the test script to only run a single file (rather than using `*.js` to test all the files in the folder?

**Edit:** Ah I just realised you're requiring the individual tests into the main `test.js` file. I guess that means we only need to run Tape with that one file?

**Comment by oliverjam** [comment]
A couple more things:

1. You can leave out the second argument to substring. It just assumes you want to go to the end of the string, which saves you specifying `ISODate.length` as the second argument.

2. Why does the `createDates` object you're exporting have a `myDate` property? Where would that be used?

**Pull request merged**
